import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  BUDGETS,
  SENTENCES,
  countSentences,
  countWords,
  measure,
  prose,
  shape,
} from '../lib/count.mjs';

test('counts the words a person reads', () => {
  assert.equal(countWords('One two three four five.'), 5);
  assert.equal(countWords(''), 0);
  assert.equal(countWords(undefined), 0);
});

test('markdown scaffolding is not reading', () => {
  // Headings, bullets, checkboxes and table pipes cost the reader nothing, so
  // only the words inside them count.
  assert.equal(countWords('## Summary'), 1);
  assert.equal(countWords('- [ ] Bug fix'), 2);
  assert.equal(countWords('| Question | Reading |\n| --- | --- |'), 2);
});

test('the template prompts nobody wrote do not count', () => {
  assert.equal(countWords('<!-- What does this PR change, and why? -->\n\nIt renames a flag.'), 4);
});

test('a fenced block is evidence, not prose', () => {
  const body = 'The failing check:\n\n```\nnpm run gates\nFAIL test (shard 1)\n```\n\nFixed.';
  assert.equal(countWords(body), 4);
});

test('the attribution footer does not count', () => {
  const generated = 'A short body.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
  assert.equal(countWords(generated), 3);
  const withEmoji =
    'A short body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)';
  assert.equal(countWords(withEmoji), 3);
});

test('a link reads as its text, and a bare URL is a click', () => {
  assert.equal(countWords('See [the audio doc](https://example.com/a/b/c).'), 4);
  assert.equal(countWords('The frame:\nhttps://github.com/o/r/blob/abc/docs/x.png'), 2);
});

test('measure reports the overage per surface', () => {
  const long = 'word '.repeat(BUDGETS.comment + 12);
  const reading = measure('comment', long);
  assert.equal(reading.words, BUDGETS.comment + 12);
  assert.equal(reading.budget, BUDGETS.comment);
  assert.equal(reading.over, 12);
  assert.equal(reading.label, 'Comment');
  assert.equal(measure('pr', 'two words').over, 0);
  assert.throws(() => measure('essay', 'x'), /unknown surface/);
});

test('the surfaces CLAUDE.md names all have a budget', () => {
  assert.deepEqual(Object.keys(BUDGETS).sort(), ['comment', 'issue', 'pr']);
  assert.ok(BUDGETS.pr > BUDGETS.issue && BUDGETS.issue > BUDGETS.comment);
});

test('prose leaves the words alone', () => {
  assert.match(prose('a **bold** claim'), /bold/);
});

test('a sentence ends at a stop, and a bullet without one is still a claim', () => {
  assert.equal(countSentences('One. Two! Three?'), 3);
  assert.equal(countSentences('No stop at all'), 1);
  assert.equal(countSentences(''), 0);
  assert.equal(countSentences('- A thing\n- Another thing'), 2);
  assert.equal(countSentences('A long\nwrapped sentence.\n\nA new paragraph.'), 2);
});

test('code, abbreviations and decimals end no sentence', () => {
  assert.equal(countSentences('`a. b` is code.'), 1);
  assert.equal(countSentences('Pick one, e.g. the first.'), 1);
  assert.equal(countSentences('The Commune is paid to 0.34%.'), 1);
  assert.equal(countSentences('See [the doc](https://example.com/a.b). Done.'), 2);
});

const body = (options = '') =>
  [
    '## Problem',
    '',
    'The loop stops on a design call. Nothing ships.',
    '',
    options,
    '## Solution',
    '',
    'The loop decides and says so. `dev-loop.test` proves it.',
    '',
    'Fixes #12',
    '',
    '- [ ] `npm run gates` passes',
    '',
    '---',
    '_Generated by [Claude Code](https://claude.ai/code)_',
  ].join('\n');

test('a pull request body is read section by section', () => {
  const { readings, missing, over } = shape(body());
  assert.deepEqual(
    readings.map((r) => [r.name, r.sentences]),
    [
      ['problem', 2],
      ['solution', 2],
    ]
  );
  assert.deepEqual(missing, []);
  assert.equal(over, false);
});

test('the closing keyword and the checklist are bookkeeping, not sentences', () => {
  const solution = shape(body()).readings.find((r) => r.name === 'solution');
  assert.equal(solution.sentences, 2);
});

test('each option is capped on its own', () => {
  const options = [
    '## Options',
    '',
    '- **Stop (current).** Nothing ships. A person decides later.',
    '- **Decide (recommended, taken).** The loop picks. The PR says which.',
    '  A reviewer can flip it. One too many.',
    '',
  ].join('\n');
  const { readings, over } = shape(body(options));
  const [first, second] = readings.filter((r) => r.name.startsWith('option'));
  assert.equal(first.sentences, 2);
  assert.equal(second.sentences, 4);
  assert.equal(second.over, 1);
  assert.equal(second.limit, SENTENCES.option);
  assert.equal(over, true);
});

test('a body without the shape says what is missing, and Options is optional', () => {
  assert.deepEqual(shape('## Summary\n\nHi.').missing, ['problem', 'solution']);
  assert.equal(
    shape(body()).readings.some((r) => r.name.startsWith('option')),
    false
  );
});

test('the template itself carries no sentences', async () => {
  const { readFileSync } = await import('node:fs');
  const template = readFileSync(
    new URL('../../../.github/PULL_REQUEST_TEMPLATE.md', import.meta.url),
    'utf8'
  );
  const { readings, missing } = shape(template);
  assert.deepEqual(missing, []);
  assert.ok(readings.every((r) => r.sentences === 0));
});
