import { test } from 'node:test';
import assert from 'node:assert/strict';

import { BUDGETS, countWords, measure, prose } from '../lib/count.mjs';

test('counts the words a person reads', () => {
  assert.equal(countWords('One two three four five.'), 5);
  assert.equal(countWords(''), 0);
  assert.equal(countWords(undefined), 0);
});

test('markdown scaffolding is not reading', () => {
  // Headings, bullets, checkboxes and table pipes cost the reader nothing, so
  // only the words inside them count.
  assert.equal(countWords('## Summary'), 1);
  assert.equal(countWords('- [ ] Bug fix'), 2);
  assert.equal(countWords('| Question | Reading |\n| --- | --- |'), 2);
});

test('the template prompts nobody wrote do not count', () => {
  assert.equal(countWords('<!-- What does this PR change, and why? -->\n\nIt renames a flag.'), 4);
});

test('a fenced block is evidence, not prose', () => {
  const body = 'The failing check:\n\n```\nnpm run gates\nFAIL test (shard 1)\n```\n\nFixed.';
  assert.equal(countWords(body), 4);
});

test('the attribution footer does not count', () => {
  const generated = 'A short body.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
  assert.equal(countWords(generated), 3);
  const withEmoji = 'A short body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)';
  assert.equal(countWords(withEmoji), 3);
});

test('a link reads as its text, and a bare URL is a click', () => {
  assert.equal(countWords('See [the audio doc](https://example.com/a/b/c).'), 4);
  assert.equal(countWords('The frame:\nhttps://github.com/o/r/blob/abc/docs/x.png'), 2);
});

test('measure reports the overage per surface', () => {
  const long = 'word '.repeat(BUDGETS.comment + 12);
  const reading = measure('comment', long);
  assert.equal(reading.words, BUDGETS.comment + 12);
  assert.equal(reading.budget, BUDGETS.comment);
  assert.equal(reading.over, 12);
  assert.equal(reading.label, 'Comment');
  assert.equal(measure('pr', 'two words').over, 0);
  assert.throws(() => measure('essay', 'x'), /unknown surface/);
});

test('the surfaces CLAUDE.md names all have a budget', () => {
  assert.deepEqual(Object.keys(BUDGETS).sort(), ['comment', 'issue', 'pr']);
  assert.ok(BUDGETS.pr > BUDGETS.issue && BUDGETS.issue > BUDGETS.comment);
});

test('prose leaves the words alone', () => {
  assert.match(prose('a **bold** claim'), /bold/);
});
